name: build and test

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

permissions: {}

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: 🔎 checking for changes
        uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        id: filter
        with:
          filters: |
            changed:
              - '.github/workflows/**'
              - 'src/generator/**'
              - 'src/netex/**'
              - 'src/siri/**'
              - 'src/General.targets'
              - 'src/Directory.Packages.props'
              - 'packages/**'
              - 'global.json'
              - 'Spillgebees.Transmodel.slnx'

  build-and-test:
    needs: [changes]
    uses: ./.github/workflows/build-test-publish.yml
    permissions:
      contents: read
    with:
      should-run: ${{ needs.changes.outputs.changed }}
