name: build and test

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - name: 🔎 checking for changes
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4
        id: filter
        with:
          filters: |
            changed:
              - 'src/generator/**'
              - 'src/netex/**'
              - 'src/siri/**'
              - 'src/General.targets'
              - 'src/Directory.Packages.props'
              - 'packages/**'
              - 'global.json'
              - 'Spillgebees.Transmodel.slnx'

  build-and-test:
    needs: [changes]
    uses: ./.github/workflows/build-test-publish.yml
    with:
      should-run: ${{ needs.changes.outputs.changed }}
